name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (default: 0.1.0)'
        required: false
        default: '0.1.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -r requirements.txt
        
    - name: Update version in setup.py
      run: |
        if [ -f "setup.py" ]; then
          sed -i "s/version=.*,/version='${{ github.event.inputs.version || '0.1.0' }}',/g" setup.py
        else
          echo "setup.py not found, please ensure it exists with proper version configuration"
          exit 1
        fi
        
    - name: Build package
      run: python -m build
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: false
